#define INC_httpmodule_T 1
/*
 * TYPEDEFS
 */
typedef struct MHTTPmodule__CRequest__S MHTTPmodule__CRequest;
typedef struct MHTTPmodule__CResponse__S MHTTPmodule__CResponse;
typedef struct MHTTPmodule__CFileServlet__S MHTTPmodule__CFileServlet;
typedef struct MHTTPmodule__CStringServlet__S MHTTPmodule__CStringServlet;
typedef struct MHTTPmodule__CFunctionServlet__S MHTTPmodule__CFunctionServlet;
typedef struct MHTTPmodule__CServer__S MHTTPmodule__CServer;
