# #####################################################################
# Automatically generated by qmake (2.01a) ?? 12? 19 20:38:34 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tipwindow.h \
    gotocelldialog.h
SOURCES += main.cpp \
    tipwindow.cpp \
    gotocelldialog.cpp
FORMS += gotocelldialog.ui
