######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 23 17:19:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h sortdialog.h tipwindow.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += gotocelldialog.cpp main.cpp sortdialog.cpp tipwindow.cpp
