######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 11 22:26:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h breakout.h brick.h paddle.h
SOURCES += ball.cpp breakout.cpp brick.cpp main.cpp paddle.cpp
