######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 18 23:40:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h mainwindow.h sortdialog.h spreadsheet.h
SOURCES += finddialog.cpp main.cpp mainwindow.cpp sortdialog.cpp spreadsheet.cpp
