######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 23:04:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
