######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 12:39:21 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fd.h finddialog.h mainwindow.h sortdialog.h spreadsheet.h
SOURCES += finddialog.cpp main.cpp mainwindow.cpp sortdialog.cpp spreadsheet.cpp
