/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class getdata */

#ifndef _Included_getdata
#define _Included_getdata
#ifdef __cplusplus
extern "C" {
#endif
#undef getdata_FOCUS_TRAVERSABLE_UNKNOWN
#define getdata_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef getdata_FOCUS_TRAVERSABLE_DEFAULT
#define getdata_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef getdata_FOCUS_TRAVERSABLE_SET
#define getdata_FOCUS_TRAVERSABLE_SET 2L
#undef getdata_TOP_ALIGNMENT
#define getdata_TOP_ALIGNMENT 0.0f
#undef getdata_CENTER_ALIGNMENT
#define getdata_CENTER_ALIGNMENT 0.5f
#undef getdata_BOTTOM_ALIGNMENT
#define getdata_BOTTOM_ALIGNMENT 1.0f
#undef getdata_LEFT_ALIGNMENT
#define getdata_LEFT_ALIGNMENT 0.0f
#undef getdata_RIGHT_ALIGNMENT
#define getdata_RIGHT_ALIGNMENT 1.0f
#undef getdata_serialVersionUID
#define getdata_serialVersionUID -7644114512714619750i64
#undef getdata_serialVersionUID
#define getdata_serialVersionUID 4613797578919906343i64
#undef getdata_INCLUDE_SELF
#define getdata_INCLUDE_SELF 1L
#undef getdata_SEARCH_HEAVYWEIGHTS
#define getdata_SEARCH_HEAVYWEIGHTS 1L
#undef getdata_NOT_OBSCURED
#define getdata_NOT_OBSCURED 0L
#undef getdata_PARTIALLY_OBSCURED
#define getdata_PARTIALLY_OBSCURED 1L
#undef getdata_COMPLETELY_OBSCURED
#define getdata_COMPLETELY_OBSCURED 2L
#undef getdata_WHEN_FOCUSED
#define getdata_WHEN_FOCUSED 0L
#undef getdata_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define getdata_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef getdata_WHEN_IN_FOCUSED_WINDOW
#define getdata_WHEN_IN_FOCUSED_WINDOW 2L
#undef getdata_UNDEFINED_CONDITION
#define getdata_UNDEFINED_CONDITION -1L
#undef getdata_IS_DOUBLE_BUFFERED
#define getdata_IS_DOUBLE_BUFFERED 0L
#undef getdata_ANCESTOR_USING_BUFFER
#define getdata_ANCESTOR_USING_BUFFER 1L
#undef getdata_IS_PAINTING_TILE
#define getdata_IS_PAINTING_TILE 2L
#undef getdata_IS_OPAQUE
#define getdata_IS_OPAQUE 3L
#undef getdata_KEY_EVENTS_ENABLED
#define getdata_KEY_EVENTS_ENABLED 4L
#undef getdata_FOCUS_INPUTMAP_CREATED
#define getdata_FOCUS_INPUTMAP_CREATED 5L
#undef getdata_ANCESTOR_INPUTMAP_CREATED
#define getdata_ANCESTOR_INPUTMAP_CREATED 6L
#undef getdata_WIF_INPUTMAP_CREATED
#define getdata_WIF_INPUTMAP_CREATED 7L
#undef getdata_ACTIONMAP_CREATED
#define getdata_ACTIONMAP_CREATED 8L
#undef getdata_CREATED_DOUBLE_BUFFER
#define getdata_CREATED_DOUBLE_BUFFER 9L
#undef getdata_IS_PRINTING
#define getdata_IS_PRINTING 11L
#undef getdata_IS_PRINTING_ALL
#define getdata_IS_PRINTING_ALL 12L
#undef getdata_IS_REPAINTING
#define getdata_IS_REPAINTING 13L
#undef getdata_WRITE_OBJ_COUNTER_FIRST
#define getdata_WRITE_OBJ_COUNTER_FIRST 14L
#undef getdata_RESERVED_1
#define getdata_RESERVED_1 15L
#undef getdata_RESERVED_2
#define getdata_RESERVED_2 16L
#undef getdata_RESERVED_3
#define getdata_RESERVED_3 17L
#undef getdata_RESERVED_4
#define getdata_RESERVED_4 18L
#undef getdata_RESERVED_5
#define getdata_RESERVED_5 19L
#undef getdata_RESERVED_6
#define getdata_RESERVED_6 20L
#undef getdata_WRITE_OBJ_COUNTER_LAST
#define getdata_WRITE_OBJ_COUNTER_LAST 21L
#undef getdata_REQUEST_FOCUS_DISABLED
#define getdata_REQUEST_FOCUS_DISABLED 22L
#undef getdata_INHERITS_POPUP_MENU
#define getdata_INHERITS_POPUP_MENU 23L
#undef getdata_OPAQUE_SET
#define getdata_OPAQUE_SET 24L
#undef getdata_AUTOSCROLLS_SET
#define getdata_AUTOSCROLLS_SET 25L
#undef getdata_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define getdata_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef getdata_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define getdata_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     getdata
 * Method:    calculate_by_MMX
 * Signature: ([I[II)[I
 */
JNIEXPORT jintArray JNICALL Java_getdata_calculate_1by_1MMX
  (JNIEnv *, jclass, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
